// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygzelivzpmrxsdqljskh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnemVsaXZ6cG1yeHNkcWxqc2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4OTMxNjYsImV4cCI6MjA1NTQ2OTE2Nn0.zmp8n7tGH-Ijz5bPvgRkGAT9gcD_1Hk2wxHkjGiAS8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);